export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_SEARCH_COST = 'SET_SEARCH_COST';
export const FETCH_CONCERT_DATA = 'FETCH_CONCERT_DATA';
export const SET_CONCERTS_COST_MIN = 'SET_CONCERTS_COST_MIN';
export const SET_CONCERTS_COST_MAX = 'SET_CONCERTS_COST_MAX';
export const IS_COST_SPECIFIED = 'IS_COST_SPECIFIED';
export const SET_FILTERED_CONCERTS = 'SET_FILTERED_CONCERTS';
